services:
  - type: web
    name: onsishop
    env: node
    plan: starter
    buildCommand: npm run render:build
    startCommand: npm run render:start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: file:./prisma/dev.db
      - key: NEXTAUTH_URL
        sync: false
      - key: NEXTAUTH_SECRET
        sync: false
      - key: JWT_SECRET
        sync: false
    disk:
      name: onsishop-disk
      mountPath: /opt/render/project/src/prisma
      sizeGB: 1